### ISSUE TITLE
DropDownList uses text-overflow: ellipsis which is never applied

### ISSUE THREAD

**Issue by austinw-fineart** [telerik/kendo-themes#1364]
**Describe the bug**
The label of the DropDownList uses the following selector:
`.k-dropdown .k-dropdown-wrap .k-input, .k-dropdowntree .k-dropdown-wrap .k-input`
which is styled with `text-overflow: ellipsis`.
However, this style is never applied because the text itself is wrapped in an anonymous flex item.

**To reproduce**
1. Go to https://demos.telerik.com/kendo-ui/dropdownlist/addnewitem
2. Add new item with very long text that exceeds the width of the list
3. No ellipsis appears on the label when item is selected

**Expected behavior**
The text should have ellipsis appear when the label exceeds the width of the list.

**Affected package (please remove the unneeded items)**
* theme-material

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Comment by joneff** [comment]
The structure of dropdown list (and similar) components is changed slightly and we now use `text-overflow: clip` instead of `ellipsis`. If you want to change the default behaviour, we now have a single unified selector:

```css
/* you can set it directly */
.k-input-value-text { text-overflow: ellipsis }

/* or scope it */
.k-dropdown-list .k-input-value-text { text-overflow: ellipsis }
```

In short, the styles that are present are applied and are correct. And we could add a setting (sass variable) for easier customization.

fixed with 6f45cf0e1c4aeeca31cf8607e7f5b16f51dec598
