### ISSUE TITLE
kendo-scheduler-toolbar does not have display:flex applied. 

### ISSUE THREAD

**Issue by smchargue** [telerik/kendo-themes#1825]
Doing a custom build of bootstrap 4.5.2 and kendo themes using kendo-thtme-boostrap.  only customizing colors. 

In Comparing a CSS build using @progress/kendo-theme-bootstrap@4.12.0 to 4.17.0 and 4.19.0  i noticed that the k-scheduler-toolbar does not have display;flex applied like it does in 4.12.0 

When i rebuild with 4.12 the kendo scheduler function as expected 

![Capture](https://user-images.githubusercontent.com/4064621/92254132-05eacb00-ee96-11ea-937b-15122e46467c.JPG)

in kendo-theme-default/scss/scheduler/_layout.scss i found this code:
``` css
kendo-scheduler .k-scheduler-toolbar {
        @include use-background-clip();
        padding: $toolbar-padding-y $toolbar-padding-x;
        border-style: solid;
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        align-items: center;
        justify-content: space-between;
    }
```
Doesn't the code above need .kendo-scheduler .k-scheduler-toolbar?  or is this a sass syntax i don't recognize?
