### ISSUE TITLE
Add ellipsis for item options

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#205]
When we set the width of the MultiSelect to be less than the width of its option items, the option items overflow:
![2018-06-05_1537](https://user-images.githubusercontent.com/20015190/40976305-65e07336-68d6-11e8-9c25-dc1976206a97.png)

Here is an example demonstrating the reported behavior:
[https://plnkr.co/edit/Dt5t4uSpuPq40RSNfSbG?p=preview](https://plnkr.co/edit/Dt5t4uSpuPq40RSNfSbG?p=preview)

As a workaround we could add the following styles:

```css
  .k-multiselect .k-button {
    max-width: calc(100% + 20px);
  }
  
  .k-multiselect .k-button > span {
      overflow: hidden;
      text-overflow: ellipsis;
      max-width: 85%;
  }
```
