### ISSUE TITLE
Add support for ReportViewer

### ISSUE THREAD

**Issue by svetq** [telerik/kendo-themes#225]
## I'm submitting a...

* Suggestion for improvement

## Current behavior
The Report Viewer is not styled properly with the provided SCSS themes for Kendo Ui for Angular:
[https://www.telerik.com/kendo-angular-ui/components/styling/](https://www.telerik.com/kendo-angular-ui/components/styling/)

## Expected behavior
The Report Viewer should be styled properly with the provided SCSS themes for Kendo Ui for Angular.

## Minimal reproduction of the problem with instructions
Load a Report Viewer in a regular CLI project as demonstrated in the following article:
[https://docs.telerik.com/reporting/angular-report-how-to-use-with-angular-cli](https://docs.telerik.com/reporting/angular-report-how-to-use-with-angular-cli)

Instead of loading the styles in index.html as follows:
`<link href="http://kendo.cdn.telerik.com/2016.3.914/styles/kendo.common.min.css" rel="stylesheet" />`
`<link href="http://kendo.cdn.telerik.com/2016.3.914/styles/kendo.default.min.css" rel="stylesheet" />`

include the SCSS theme in styles.css:
`@import "~@progress/kendo-theme-default/dist/all.css";`

## Environment
Product:

* Kendo Ui for Angular

## Workaround

We can include the following additional styles to the styles.css file in order to display the Report Viewer properly:

```scss
@import "~@progress/kendo-theme-default/dist/all.css";
 
.trv-nav .k-menu,
.trv-nav .k-menu .k-item {
  height: auto !important;
}
.trv-nav .k-menu > .k-item,
.trv-nav .k-menu > .k-item > .k-link {
  display: inline-flex;
}
```
