### ISSUE TITLE
Spreadsheet should use normal line height

### ISSUE THREAD

**Issue by mishoo** [telerik/kendo-themes#251]
When doing row height auto-adjustment, the spreadsheet assumes standard line height (see https://github.com/telerik/kendo-ui-core/issues/3956#issuecomment-412465381).  The following should be added:

```css
.k-spreadsheet-cell { line-height: normal }
```

(currently in the SASS themes, a cell's line height is 1.5, inherited from `.k-widget`)
