### ISSUE TITLE
dropdownlist behaves like button

### ISSUE THREAD

**Issue by AndersMad** [telerik/kendo-themes#2822]
The dropdownlist styles "behaves" like button (`$dropdownlist-bg: $button-bg`) but the standard html select does not.

1) I would like to request an option for this e.g. `$kendo-style-dropdown-as-select: 1;` and then dropdown _variables.scss could conditionally `@if` that.

I can override the variables, but it's a bit tricky as it has to happen between variables and usage. E.g. `$dropdownlist-bg: $input-bg;`. But even when doing so:

2) The `.k-select` is missing styles - like the combobox has.

**Comment by joneff** [comment]
Just to make sure, you would like to have styles for the following selecttor `select.k-dropdown`?

**Comment by AndersMad** [comment]
In combobox it goes:
`$combobox-bg: $input-bg !default;`

But in kendo-theme-default\scss\dropdownlist\_variables.scss the styles goes:
`$dropdownlist-bg: $button-bg !default;`

It would be really nice if it whet e.g. like:
```scss
@if ($style-dropdown-as-a-normal-select-or-same-as-combox-not-as-a-button) {
    $dropdownlist-bg: $input-bg !default;
    ...
} else {
    $dropdownlist-bg: $button-bg !default;
    ...
}
```

If that feature is done - the dropdownlist will need styling on the select button just as in combobox:
```scss
.k-select {
    @include fill(
        $dropdownlist-select-text,
        $dropdownlist-select-bg,
        $dropdownlist-select-border,
        $dropdownlist-select-gradient
    );
}
```
With new variables and for hover etc.
