### ISSUE TITLE
SASS Variables for Loading Indicator

### ISSUE THREAD

**Issue by DaleyKD** [telerik/kendo-themes#2910]
**Is your feature request related to a problem? Please describe.**
I'm trying to style the loading indicator using SASS. Instead of using `$component-bg` for the `k-loading-color`, it'd be nice to have a variable directly associated to this. Also opacity, z-index, and a way to easily set the color.

**Describe the solution you would like to see implemented**
Add some additional variables to help.

**Describe the alternatives you have considered**
I'm doing the following for now:
``` scss
// Override the scrim color
.k-loading-color {
	background-color: #333 !important;
	opacity: .25 !important;
}

.k-loading-mask {
	z-index: $zindex-tooltip + 1;
}

// Override the loading indicator color
.k-loading {
	color: $primary;
}
```
