### ISSUE TITLE
kendoValidator tooltip background color not applied

### ISSUE THREAD

**Issue by mikestu** [telerik/kendo-themes#397]
I noticed that the kendoValidator tooltips are appearing with a black background in our app now, and it seems to be because the variables below are using a function called "color-level" that no longer exists in Bootstrap (that I can find).  I think it may have been renamed to theme-color-level, but that didn't work for me either.  In our generated CSS, it actually shows the function name now, like:

```scss
.k-tooltip-validation {
    border-color: color-level(#ffc107,9);
    color: color-level(#ffc107,-6);
    background-color: color-level(#ffc107,10)
}

// Notification
$notification-info-bg: color-level($info, 10) !default;
$notification-info-text: color-level($info, -6) !default;
$notification-info-border: color-level($info, 9) !default;
$notification-success-bg: color-level($success, 10) !default;
$notification-success-text: color-level($success, -6) !default;
$notification-success-border: color-level($success, 9) !default;
$notification-warning-bg: color-level($warning, 10) !default;
$notification-warning-text: color-level($warning, -6) !default;
$notification-warning-border: color-level($warning, 9) !default;
$notification-error-bg: color-level($error, 10) !default;
$notification-error-text: color-level($error, -6) !default;
$notification-error-border: color-level($error, 9) !default;
```
