### ISSUE TITLE
Invalid selector for Skeleton animation styles in Fluent theme generated from the ThemeBuilder

### ISSUE THREAD

**Issue by ntacheva** [telerik/kendo-themes#4094]
**Describe the bug**

I downloaded a theme from the ThemeBuilder targeting the Fluent theme as a base. It contains the following styles for the Skeleton animation:

````CSS
.k-skeleton-pulse .k-skeleton{
    animation:k-skeleton-pulse 1.5s ease-in-out .5s infinite
}
````
This results in missing animation in Blazor Skeleton. The component actually has both classes  - `.k-skeleton` and `.k-skeleton-animation_type`. So, the above-listed selector listed is not valid (including space).

For reference, the animation styles in the Default theme look like so:

````CSS
.k-skeleton-pulse .k-skeleton, .k-skeleton-pulse.k-skeleton {
    -webkit-animation: k-skeleton-pulse 1.5s ease-in-out .5s infinite;
    animation: k-skeleton-pulse 1.5s ease-in-out .5s infinite
}
````

**Public report**: [1585556](https://feedback.telerik.com/blazor/1585556-invalid-selector-for-skeleton-animation-styles)

**Expected behavior**

Skeleton styles should use valid selectors.

**Affected package (please remove the unneeded items)**
* theme-fluent

**Affected suites**
* Telerik UI for Blazor

**Affected browsers**
* All
