### ISSUE TITLE
Calendar cell size and border in kendo-theme-material

### ISSUE THREAD

**Issue by kspeyanski** [telerik/kendo-themes#445]
We've found two issues with the components:

- The cell element of the `Calendar` and `MultiViewCalendar` is stretching due to the following rule:
```css
.k-calendar tbody th {
    padding-left: 16px;
    padding-right: 16px;
}
```
Used initially for the month label.

Looks like that:
![image](https://user-images.githubusercontent.com/30626787/48559610-9dafab80-e8f4-11e8-841b-77ca8a5c798e.png)

- Incorrect border radius on `k-weekend`
When the calendar is in range-selection mode, it's range-start and range-end cells have border-radius only on the outer side.
```css
.k-calendar.k-calendar-range .k-range-start {
    border-color: inherit;
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
}
```
**BUT**, the `k-weekend` class overrides this to:
```css
.k-calendar .k-content .k-weekend {
    border-radius: 0;
    opacity: 1;
}
```

> Can be observed in the image above.

### Both issues are observed in Angular and React, dev and latest channels. 
[stackblitz example for refference](https://stackblitz.com/edit/angular-in3fdi?file=index.html)
