### ISSUE TITLE
Kendo Grid should not have hover effect if not selectable

### ISSUE THREAD

**Issue by akloeber** [telerik/kendo-themes#464]
## I'm submitting a...

* Bug report 

## Current behavior
Right now, Kendo Grid always shows a hover effect even if the `selectable` input of the grid component is set to `false`.

## Expected behavior
If the user can not interact with a row (`selectable == false`) there should not be a hover effect at all.

## Environment
Product:

* Kendo Ui for Angular

Package versions:

```
@progress/kendo-theme-default@2.61.0
```

Browser:

- Chrome (desktop) version 70.0.3538.77

System:
- TypeScript version: 2.9.2
- Node version: 8.11.3
- Platform:  Mac OS

**Comment by joneff** [comment]
While you do make a great point, having a hover effect is something that's part of the theme and not strictly speaking related to functionality of the grid.

The quickest way to resolve the issue, only on demand is via css:
```css
.k-grid-content .k-grid-table {
    pointer-events: none;
}
```

That will, however, apply the styles to all grids, so if you want to scope the styles, say by adding a class to editable grids:
```css
/* assuming you add .k-grid-editable to grids that can be edited */
.k-grid:not(.k-grid-editable) .k-grid-content .k-grid-table {
    pointer-events: none;
}
```
