### ISSUE TITLE
Missing styles related to table resizing

### ISSUE THREAD

**Issue by radkostanev** [telerik/kendo-themes#4770]
**Describe the bug**
When the Editor component has its edit mode set to 'div', all styles related to table resizing are missing.

**To reproduce**

1. Go to https://blazorrepl.telerik.com/mnbknPYM43T4JDro14
1. Select any cell.
1. Notice resize handles appear but are mispositioned. Also notice that row and column resizing is not possible.
1. Also notice that the resize handles of the image below the table are correctly positioned and work as expected.

**Expected behavior**
The table resizing functionality should continue to work despite the edit mode.

**Screenshots**
![image](https://github.com/telerik/kendo-themes/assets/49035696/582af0d6-b735-4a12-9565-2ea851673f91)

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable

**Additional context**
Currently we set various styles that are necessary for different operations, such as the following style for image resizing: https://github.com/telerik/kendo-themes/blob/master/packages/fluent/scss/editor/_layout.scss#L58-L61

However, we have not provided any styles necessary for table resizing. To be exact, the following classes should be added to the themes for the above example to work as expected: 

<details>
  <summary>CSS that should be added</summary>
  
  ```css
    .k-editor-resize-wrap-element {
      display: inline-block;
      position: relative;
    }

    .ProseMirror.resize-cursor {
      cursor: ew-resize;
      cursor: col-resize;
    }

    .ProseMirror.resize-cursor-vertical {
      cursor: sn-resize;
      cursor: row-resize;
    }

    .ProseMirror .column-resize-handle {
      position: absolute;
      right: -2px; top: 0; bottom: 0;
      width: 4px;
      z-index: 20;
      background-color: #adf;
      pointer-events: none;
    }

    .ProseMirror .row-resize-handle {
      position: absolute;
      right: 0; left: 0; bottom: 0;
      transform: translate(0, 50%);
      height: 4px;
      z-index: 20;
      background-color: #adf;
      pointer-events: none;
    }
  ```
</details>

Here is a REPL link with the above-mentioned styles and the final result: https://blazorrepl.telerik.com/QxbEdbas477u1pfT53
