### ISSUE TITLE
Badge component z-index 9999

### ISSUE THREAD

**Issue by mbechev** [telerik/kendo-themes#5025]
`.k-badge-edge` class has a **z-index** property set to 9999. Does it need such a big **z-index**?

```css
.k-badge-edge {
    position: absolute;
    z-index: 9999;
}
```

**Background of the discussion**
We tried using the badge inside a Grid cell, but opening a popup appears behind the badge.
<img width="231" alt="image" src="https://github.com/telerik/katana/assets/33104481/098d0894-6f16-4b4c-a210-39f10b8ba00d">
https://stackblitz.com/edit/angular-ramb33?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts
