### ISSUE TITLE
Read-only Acro field values are not rendered in the PDF Viewer

### ISSUE THREAD

**Issue by Stamo-Gochev** [telerik/kendo-themes#5352]
**Describe the bug**

Similar to https://github.com/telerik/kendo-themes/issues/5256, fixing the bug https://github.com/telerik/kendo-pdfviewer-common/issues/116 requires adding styles for the acro fields.

**To reproduce**
See https://github.com/telerik/kendo-pdfviewer-common/issues/116#issue-2884370524

**Expected behavior**

The following styles need to be added to the themes:

```css
.k-annotation-layer .k-annotation-content {
    position: absolute;
    width: 100%;
    height: 100%;
    pointer-events: none;
}
```

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable
* OS: [for example, Windows, Linux, Mac]
* Node version: [for example, 10.15.3]
* NPM version: [for example, 6.4.1]

**Additional context**
Add any other context about the bug.
