### ISSUE TITLE
PDFViewer Form Filling

### ISSUE THREAD

**Issue by alestoya** [telerik/kendo-themes#5409]
**Describe the bug**
Identical to https://github.com/telerik/kendo-themes/issues/5352 adding additional widgets within the boundaries of the PDFViewer would require some styles.

**To reproduce**

1. Go to https://github.com/telerik/kendo-pdfviewer-common/pull/122#issue-2965421041

**Expected behavior**
The following styles should be added:

```CSS
.k-annotation-layer {
    --annotation-unfocused-field-background: url(data:image/svg+xml;charset=UTF-8,<svg width='1px' height='1px' xmlns='http://www.w3.org/2000/svg'><rect width='100%' height='100%' style='fill:rgba(0, 54, 255, 0.13);'/></svg>);
    --input-focus-border-color: black;
    --input-focus-outline: 1px solid Canvas;
    --input-unfocused-border-color: transparent;
    --input-disabled-border-color: transparent;
    --input-hover-border-color: black;
    --link-outline: none;
}

.k-annotation-layer .k-text-widget-annotation:is(input,textarea), .k-annotation-layer .k-button-widget-annotation:is(.k-checkbox-widget-annotation, .k-radio-button-widget-annotation) input {
    background-image: var(--annotation-unfocused-field-background);
    border: 2px solid var(--input-unfocused-border-color);
    box-sizing: border-box;
    font: calc(9px* var(--total-scale-factor)) sans-serif;
    height: 100%;
    margin: 0;
    vertical-align: top;
    width: 100%;
}

.k-annotation-content {
    position: absolute;
    width: 100%;
    height: 100%;
    pointer-events: none;
}

.k-annotation-layer {
    :is(.k-link-annotation, .k-button-widget-annotation.k-push-button-widget-annotation) > a {
        position: absolute;
        font-size: 1em;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
    }
}

.k-annotation-layer {
    :is(.k-link-annotation, .k-button-widget-annotation.k-push-button-widget-annotation):not(.hasBorder) > a:hover {
        opacity: 0.2;
        background-color: rgb(255 255 0);
        box-shadow: 0 2px 10px rgb(255 255 0);
    }
}

```

**Screenshots**

**Affected package (please remove the unneeded items)**
* theme-default
* theme-bootstrap
* theme-material
* theme-tasks

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Kendo UI for Angular
* Kendo UI for React
* Kendo UI for Vue
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All

**Build system information (please remove the unneeded items)**
* Not Applicable
* OS: [for example, Windows, Linux, Mac]
* Node version: [for example, 10.15.3]
* NPM version: [for example, 6.4.1]

**Additional context**
Add any other context about the bug.
