### ISSUE TITLE
Disabled Styles Globally Affect All Elements in kendo-theme-default@11.0.1

### ISSUE THREAD

**Issue by PavelMaskevichFromFlynn** [telerik/kendo-themes#5458]
**Describe the bug**  
In `kendo-theme-default@11.0.1`, the global CSS selector for disabled styles has changed from targeting only Kendo elements to targeting all elements. This causes the disabled styling to be applied globally, potentially breaking other components or custom elements not related to Kendo UI.

**To reproduce**  
1. Install `kendo-theme-default@11.0.1` in your project.
2. Add any non-Kendo HTML element with the `disabled` attribute (for example, a custom button or an unrelated input).
3. Observe that the global disabled styles are now applied to all elements with the `disabled` attribute, not just Kendo UI components.

**Expected behavior**  
Disabled styles should only be applied to Kendo UI elements, as in previous versions (e.g., 10.6.0). Non-Kendo elements should not be affected by Kendo UI's CSS rules.

**Affected package (please remove the unneeded items)**  
* theme-default

**Affected suites (please remove the unneeded items)**  
* Kendo UI for jQuery  
* Kendo UI for Angular  
* Kendo UI for React  
* Kendo UI for Vue  
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**  
* All

**Build system information (please remove the unneeded items)**  
* Not Applicable

**Additional context**  
In `kendo-theme-default@10.6.0`, the selector was:
```css
.k-disabled,.k-widget[disabled],.k-disabled{
    outline:none;
    cursor:default;
    color:var(--kendo-disabled-text, unset);
    background-color:var(--kendo-disabled-bg, unset);
    border-color:var(--kendo-disabled-border, unset);
    opacity:var(--kendo-disabled-opacity, unset);
    filter:var(--kendo-disabled-filter, unset);
    pointer-events:none;
    box-shadow:none
}
```
In `kendo-theme-default@11.0.1`, it is:
```css
.k-disabled,[disabled],:disabled{
    outline:none;
    cursor:default;
    color:var(--kendo-disabled-text, unset);
    background-color:var(--kendo-disabled-bg, unset);
    border-color:var(--kendo-disabled-border, unset);
    opacity:var(--kendo-disabled-opacity, unset);
    filter:var(--kendo-disabled-filter, unset);
    pointer-events:none;
    box-shadow:none
}
```
The addition of `[disabled], :disabled` means the style is now applied to every element with a `disabled` attribute or the `:disabled` pseudo-class, regardless of whether it is a Kendo component.
