### ISSUE TITLE
FileManager ListView displays unwanted empty space between the tiles

### ISSUE THREAD

**Issue by dimodi** [telerik/kendo-themes#5493]
**Describe the bug**

The FileManager displays file icons in ListView mode with a `align-content: space-evenly` style.

**To reproduce**

https://blazorrepl.telerik.com/GfaqFZvO25eXl0ss39

**Expected behavior**

```css
.k-filemanager-listview {
    align-content: flex-start;
}
```

**Affected suites (please remove the unneeded items)**
* Kendo UI for jQuery
* Telerik UI for ASP.NET Core
* Telerik UI for ASP.NET MVC
* Telerik UI for Blazor

**Affected browsers (please remove the unneeded items)**
* All
